version: "3"

services:
    nominatim:
        container_name: nominatim
        image: mediagis/nominatim:4.4
        ports:
            - "8080:8080"
        environment:
            PBF_URL: https://download.geofabrik.de/south-america/argentina-latest.osm.pbf
            REPLICATION_URL: https://download.geofabrik.de/south-america/argentina-updates/
            NOMINATIM_PASSWORD: very_secure_password
        volumes:
            - nominatim-data:/var/lib/postgresql/14/main
        shm_size: 1gb

volumes:
    nominatim-data: